name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH and add private key
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      # Step 3: Deploy the application to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            echo "Navigating to project directory on EC2..."
            cd /home/ubuntu/Project-Management-App---Server

            echo "Resetting and pulling the latest changes from GitHub..."
            git reset --hard
            git pull origin main

            echo "Installing dependencies..."
            npm ci --include=dev

            echo "Restarting the PM2 process..."
            pm2 restart project-management || pm2 start dist/src/index.js --name project-management

            echo "Saving PM2 state and enabling startup on reboot..."
            pm2 save
            sudo env PATH=$PATH:$(which node) $(which pm2) startup systemd -u $EC2_USER --hp /home/$EC2_USER

            echo "Deployment completed successfully!"
          EOF

